version: '3.5'
services:
  app:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    restart: unless-stopped
    ports:
      - 8080:8080
    volumes:
      - ../:/app
    command: npm run start
