version: "3.5"
services:
    app:
        build:
            context: ../
            dockerfile: docker/Dockerfile
        restart: unless-stopped
        ports:
            - 9358:9358
        volumes:
            - ../:/app
        container_name: node-pdfs
        command: npm run start
